export { default as HomePage } from './home/HomePage.jsx'
export { default as AboutPage } from './about/AboutPage.jsx'
export { default as FinancialPlanningPage } from './services/financial-planning/FinancialPlanningPage.jsx'
export { default as InvestmentManagementPage } from './services/investment-management/InvestmentManagementPage.jsx'
export { default as InsurancePage } from './services/insurance/InsurancePage.jsx'
export { default as ACPIPage } from './acpi/ACPIPage.jsx'
export { default as ContactPage } from './contact/ContactPage.jsx'